name: 'azurediagramsgithubactions'
description: 'Runs AzureDiagramGenerator (as dotnet tool)'
branding:
  icon: 'command'
  color: 'green'
inputs:
  subscriptionId:
    description: 'Azure Subscription Id'
    required: true
  resourceGroup:
    description: 'Azure Resource Group to match on. Regexes supported. Also * can be used as a simple non greedy wildcard (he*o) will match a resource group called hello'
    required: true
  condensed:
    description: 'Collapse private endpoints / vm disks to produce a simple view. Useful for large architectures'
    required: false
    default: 'true'
  showDiagnostics:
    description: 'Show flows from services to diagnostics like App Insights / Azure Monitor'
    required: false
    default: 'false'
  showIdentity:
    description: 'Show connection from services to AAD for Managed Identities'
    required: false
    default: 'false'
  showRuntime:
    description: 'Show runtime flows defined on the management plane (e.g. container pulls)'
    required: false
    default: 'true'
  showInferred:
    description: 'Look into configuration settings to infer more links between resources'
    required: false
    default: 'false'
  outputFileName:
    description: 'Output file name to write to (will write to the working directory)'
    required: true
runs:
  using: 'composite'
  steps:
    - run: dotnet tool install --global AzureDiagramGenerator --version 0.6.31
      shell: bash
    - run: |
        AzureDiagramGenerator --subscription-id "${{ inputs.subscriptionId }}" \
                              --resource-group "${{ inputs.resourceGroup }}" \
                              --output-file-name "${{ inputs.outputFileName }}" \
                              --condensed "${{ inputs.condensed == 'true' }}" \
                              --show-diagnostics "${{ inputs.showDiagnostics == 'true' }}" \
                              --show-identity "${{ inputs.showIdentity == 'true' }}" \
                              --show-runtime "${{ inputs.showRuntime == 'true' }}"
                              --show-inferred "${{ inputs.showInferred == 'true' }}"
                              --output-png false
      shell: bash
